[project]
name = "sales-decline-forecasting"
version = "0.1.0"
description = ""
authors = [
    {name = "ANN"}
]

readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastparquet>=2024.11.0",
    "holidays>=0.71",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "psycopg2>=2.9.10",
    "pydantic-settings>=2.9.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.40",
    "statsmodels>=0.14.4",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
]
